# Generated by Django 3.1 on 2020-08-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='background_color',
            field=models.CharField(default='red.jpg', max_length=100),
        ),
    ]
